name: Test Smooch Package
description: Run test suite against Smooch package tarball
inputs:
  node-version:
    default: 16
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    
    - run: npm ci
      shell: bash
    - uses: actions/download-artifact@v4
      with:
        name: smooch.tgz
        path: ./

    - run: npm run test
      shell: bash
